application_adyma/urls.py
from django.urls import path

from . import views



urlpatterns = [

path('inscription_individuel/', views.inscription_individuel, name='inscription_individuel'),
path('diagnostic_psycho-social/', views.diagnostic_psychosocial, name='diagnostic_psychosocial'),
path('diagnostic_physique_RESIDENCE/', views.diagnostic_physique_residence, name='diagnostic_physique_residence'),
path('diagnostic_physique_EHPAD/', views.diagnostic_physique_ehpad, name='diagnostic_physique_ehpad'),
path('fiche_test/', views.fiche_test, name='fiche_test'),
path('creation_groupe/', views.creation_groupe_activite, name='creation_groupe_activite'),
path('feuille_présence/', views.fiche_presence, name='fiche_presence'),
path("feuille_d'activité/", views.fiche_activite, name='fiche_activite'),
path('inscription_structure/', views.inscription_structure, name='inscription_structure'),
path('diagnostic_structurel/', views.diagnostic_structurel, name='diagnostic_structurel'),
path('visu_structure/$', views.structure_view, name='structure_view'),
path('liste_beneficiaire/$', views.coach_liste_beneficiaire_view, name='coach_liste_beneficiaire_view'),






]
# Attention dans les fichiers HTML, dans les formulaires il y a des liens vers les vues par exemple dans 
# storage.html mettre la vue correspondante questions_save.

# Les vues good et wrong reponses ne sont pas connectées car on ne doit pas les afficher. 
# C'est en fonction de la réponse de l'utilisateur que les vues seront affichées.


# La vue du fichier question.html awnser.1  ne faut pas la changer car ça va permettre de savoir si la question est bonne ou non.

projet_adyma/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from application_adyma.views import homepage_view, coach_liste_beneficiaire_view, coach_detail_beneficiaire_view

urlpatterns = [
    path('', homepage_view, name='home'),
    path('admin/', admin.site.urls),
    path('', include('application_adyma.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('beneficiaires', coach_liste_beneficiaire_view, name='liste_beneficiaire_coach'),
    path('beneficiaires/<int:id>/', coach_detail_beneficiaire_view, name='liste_beneficiaire_coach'),


]

application_adyma/models.py
from django.db import models
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField
from django.utils import timezone
from django.contrib.auth.models import User
from datetime import date
from multiselectfield import MultiSelectField
from django.utils.translation import ugettext_lazy as _
from django.db.models import Sum
from django.conf import settings
from multiselectfield import MultiSelectField


class Coach(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, unique=True, on_delete=models.CASCADE, verbose_name = "Nom-Prenom du coach")
    date_inscription_coach = models.DateField("Date de l'inscription(jour/mois/annee)", auto_now_add=False, auto_now=False, blank=True, default=timezone.now)
    telephone_coach = PhoneNumberField(null=True, unique=True, blank=True,  verbose_name="Téléphone du coach", help_text="Format téléphone +33 puis numéro de telephone")
    mail_coach = models.EmailField(max_length=100, unique=True, blank=True, null=True, verbose_name="Email du coach")

    def __str__(self):
        return f"{self.user} "

    class Meta:
        verbose_name = "Coach"
        ordering = ['user']


class Structure(models.Model):
    nom_structure = models.ForeignKey(settings.AUTH_USER_MODEL, unique=True, on_delete=models.CASCADE, verbose_name = "Nom de la structure")
    date_inscription_structure= models.DateField(auto_now_add=False, auto_now=False, default=timezone.now, verbose_name = "Date de l'inscription(jour/mois/annee)")
    adresse_structure = models.TextField(null=True,  blank=True, max_length=200, verbose_name="Adresse")
    ville_structure= models.CharField(null=True, blank=True, max_length=50, verbose_name="Ville")
    telephone_structure = PhoneNumberField(null=True, blank=True, unique=True, verbose_name="Téléphone de la structure", help_text="Format téléphone +33 puis numéro de telephone")
    nombre_residents = models.PositiveIntegerField(null=True,  blank=True, verbose_name="Nombre de résidents", default=0)
    nom_directeur_structure= models.CharField(null=True,  blank=True, max_length=50, verbose_name = "Nom du directeur")
    mail_directeur_structure= models.EmailField(null=True,  blank=True, max_length=100,verbose_name="Email du directeur")
    telephone_directeur_structure = PhoneNumberField(null=True, blank=True, unique=True, verbose_name="Téléphone du directeur", help_text="Format téléphone +33 puis numéro de telephone")
    autres_salaries_referents = models.TextField(null=True,  blank=True, verbose_name="Autres salariés référents")
    nom_prenom_coach_1 = models.ManyToManyField(Coach,null=True,  blank=True, verbose_name="Nom-Prenom des coachs de la structure")

    def __str__(self):
        return f"{self.nom_structure} "

class Activite(models.Model):
    nom_activite = models.CharField(max_length=300, unique=True,  verbose_name="Nom de l'activité", )
    date_activite = models.DateField("Date de la fiche de présence(jour/mois/annee)", auto_now_add=False, auto_now=False, blank=True, default=timezone.now)
    type_activite = models.CharField(max_length=100 , null=True, blank=True,  verbose_name="Theme d'activité (psychologique, cardio..)")
    
    class Meta():
        verbose_name="Fiche d'activité"
        ordering=["groupe"]
        

    def __str__(self):
        return f"{self.groupe} - {str(self.date_activite) -{self.nom_activite} }"



class Groupe(models.Model):

    individuel='individuel'
    collectif='collectif'

    type_groupe =(
        (individuel, _('Individuel')),
        (collectif, _('Collectif')),
    )

    nom_groupe = models.CharField(max_length=100, unique=True, verbose_name="Nom du groupe")
    description_groupe = models.TextField()
    structure = models.ForeignKey(Structure, on_delete=models.CASCADE, verbose_name="La structure qui met en place l'activité")
    coach = models.ForeignKey(Coach, on_delete=models.CASCADE, verbose_name="Nom du coach pour le groupe d'activité")
    type_groupe = models.CharField(null=True,  blank=True, max_length=50, choices=type_groupe, default= "individuel", verbose_name="Type de groupe")
    activite_groupe = models.ManyToManyField(Activite, null=True,  blank=True, verbose_name="Les Activités du groupe")
    @property
    def Liste_des_bénéficiaires(self):
        return ",".join([str(p) for p in self.beneficiaire_groupe.all()])

    class Meta():
        verbose_name="Groupe d'activité"
        ordering=["nom_groupe"]

    def __str__(self):
        return f"{self.nom_groupe}"




class Diagnostic_structurel(models.Model):

    class Adaptation(float, models.Choices):
        Espace_adapte = (1), ("Espace bien adapté")
        Espace_peu_adapate = (0.5), ("Espace peu adapté")
        Espace_pas_adapte = (0), ("Espace pas du tout adapaté")

    class Nombre_activites(float, models.Choices):
        bcp_activite = (1), ("+ de 4 activités")
        moyen_activite = (0.5), ("Entre 2 et 4 activités")
        peu_activite = (0), ("Moins de 2 activités")

    class Salle_reservee(float, models.Choices):
        bcp_salle = (1), ("Salle bien adapatée")
        moyen_salle = (0.5), ("Salle peu adaptée")
        peu_salle = (0), ("Aucune salle réservée")

    class Materiel_activite(float, models.Choices):
        bcp_materiel = (1), ("2 matériels ou +")
        moyen_materiel = (0.5), ("1 matériel")
        peu_materiel = (0), ("Aucun matériel")

    class Liens_reguliers(float, models.Choices):
        bcp_lien = (1), ("2 liens +")
        moyen_lien = (0.5), ("1 lien")
        peu_lien = (0), ("Aucun lien")

    class Personnes_ext(float, models.Choices):
        bcp_personne = (1), ("4 personnes +")
        quelques_personne = (0.5), ("Quelques unes")
        peu_personne = (0), ("Aucune personne")

    class Sejours_organise(float, models.Choices):
        bcp_sejour = (1), ("2 sorties/séjours ou plus organisés dans l'année")
        quelques_sejour = (0.5), ("1 sortie/séjour organisé dans l'année")
        peu_sejour = (0), ("Aucune sortie/séjour organisé dans l'année")

    class Commerces_prox(float, models.Choices):
        bcp_commerce = (1), ("3 commerces ou plus à proximité")
        quelques_commerce = (0.5), ("1 ou 2 commerces à proximité")
        peu_commerce = (0), ("Aucun commerce à proximité")
    
    class Parcs_prox(float, models.Choices):
        bcp_parc = (1), ("2 parcs ou plus à proximité")
        quelquesparc = (0.5), ("1 parc à proximité")
        peu_parc = (0), ("Aucune parc à proximité")

    class Transports_prox(float, models.Choices):
        bcp_transport = (1), ("Inférieur à 250m")
        quelquestransport = (0.5), ("Entre 250m et 500m")
        peu_transport = (0), ("Supérieur à 500m")


    structure = models.ForeignKey(Structure, on_delete=models.CASCADE, verbose_name="Nom de la structure")
    date_diagnostic = models.DateField("Date du diagnostic(jour/mois/annee)", auto_now_add=False, auto_now=False, blank=True, default=timezone.now)
    adaptation_env_struc_mobi = models.FloatField(max_length=300, null=True, blank=True, choices=Adaptation.choices, verbose_name="Adaptabilité de l'environnement et de la structure à la mobilité (escaliers, barres d'appuis, luminosité...)")
    nombre_activite_semaine = models.FloatField(max_length=300, null=True, blank=True, choices=Nombre_activites.choices, verbose_name="Nombre d'activité (mémoire, gym, informatique...) par semaine proposées")
    salle_activite_reservee = models.FloatField(max_length=300, null=True, blank=True, choices=Salle_reservee.choices, verbose_name="Salle d'activité réservée pour les activités physiques")
    materiel_activite_physique = models.FloatField(max_length=300, null=True, blank=True, choices=Materiel_activite.choices, verbose_name="Matériel d'activité physique (tapis, machines, espalier)")
    liens_reguliers_org_ext  = models.FloatField(max_length=300, null=True, blank=True, choices=Liens_reguliers.choices, verbose_name="Liens réguliers avec organisation extérieure")
    nb_personnes_ext_reg_etablissement = models.FloatField(max_length=300, null=True, blank=True, choices=Personnes_ext.choices, verbose_name="Nombre de personnes extérieures venant réulièrement dans l'établissement")
    sorties_sejours_org_annee = models.FloatField(max_length=300, null=True, blank=True, choices=Sejours_organise.choices, verbose_name="Sorties et séjours organisés dans l'année")
    nb_commerces_prox = models.FloatField(max_length=300, null=True, blank=True, choices=Commerces_prox.choices, verbose_name="Nombre de commerces de proximité (< 250m)")
    nb_parcs_prox = models.FloatField(max_length=300, null=True, blank=True, choices=Parcs_prox.choices, verbose_name="Nombre de parcs à proximité (< 500m)")
    transports_communs_prox = models.FloatField(max_length=300, null=True, blank=True, choices=Transports_prox.choices, verbose_name="Transports en commun à proximité (en mètres)")

    class Meta:
        verbose_name = "Diagnostic structurel"
        ordering=["structure"]

class Beneficiaire(models.Model):
        
    equilibre = 'equilibre'
    marcher= 'marcher'
    sortir= 'sortir'
    rencontre='rencontre'
    bouger_mentretenir='bouger_mentretenir'
    aucun_interet='aucun_interet'
    peur_tomber='peur_tomber'
    perte_motivation_isolement='perte_motivation_isolement'
    fatigabilite='fatigabilite'
    perte_sens_interet='perte_sens_interet'
    aucun_frein='aucun_frein'
    douleurs='douleurs'
    souplesse='souplesse'
    renforcement_musculaire='renforcement_musculaire'
    gestes_quotidiens='gestes_quotidiens'
    remobilsation_reconditionnement='remobilsation_reconditionnement'
    endurance_gestion_effort='endurance_gestion_effort'
    gestion_stress='gestion_stress'
    coordination='coordination'
    individuel='individuel'
    collectif='collectif'


    interet_projet = [
        (equilibre, _('Equilibre')),
        (marcher, _('Marcher')),
        (sortir, _('Sortir')),
        (rencontre, _('Rencontre')),

application_adyma/forms.py
# Importation formulaires
from django import forms
from django.forms import ModelForm
from django.forms import PasswordInput

# Importation table BD
from application_adyma.models import *


# Extensions
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget
from validate_email import validate_email


class BeneficiaireForm(forms.ModelForm):
    telephone = PhoneNumberField(
        widget=PhoneNumberPrefixWidget(initial="FR")
    )
    class Meta:
        model = Beneficiaire
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        super(BeneficiaireForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'margin_checkbox',
        })


class Diagnostic_psychosocialForm(forms.ModelForm):
    class Meta:
        model = Diagnostic_psychosocial
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        super(Diagnostic_psychosocialForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'margin_checkbox',
        })
        
        
class Diagnostic_physique_residenceForm(forms.ModelForm):
    class Meta:
        model = Diagnostic_physique_residence 
        fields = '__all__'

class Diagnostic_physique_ehpadForm(forms.ModelForm):
    class Meta:
        model = Diagnostic_physique_ehpad
        fields = '__all__'

class Fiche_testForm(forms.ModelForm):
    class Meta:
        model = Fiche_test
        fields = '__all__'


class GroupeForm(forms.ModelForm):
    class Meta:
        # A REMPLIR
        model = Groupe
        fields = '__all__'


class Fiche_presenceForm(forms.ModelForm):
    class Meta:
        # A REMPLIR
        model = Fiche_presence
        fields = '__all__'

class Fiche_activiteForm(forms.ModelForm):
    class Meta:
        # A REMPLIR
        model = Fiche_test
        fields = '__all__'


class StructureForm(forms.ModelForm):
    telephone_structure = PhoneNumberField(
        widget=PhoneNumberPrefixWidget(initial="FR")
    )
    telephone_directeur_structure = PhoneNumberField(
        widget=PhoneNumberPrefixWidget(initial="FR")
    )
    class Meta:
        model = Structure
        fields = '__all__'


class Diagnostic_structurelForm(forms.ModelForm):
    class Meta:
        # A REMPLIR
        model =  Diagnostic_structurel
        fields = '__all__'








        

application_adyma/templates/application_adyma/vues/coach_liste_beneficiaire.html
{% extends "application_adyma/base.html" %}
{% block content %}
<div class="card">
    <div class="card-body">
      <h3>Liste des bénéficiaires de {{ user.username }}</h3>
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th scope="col-2">Nom-Prenom </th>
              <th scope="col-2">Date d'inscription</th>
              <th scope="col-2">Groupe d'activités</th>
              <th scope="col-2">Structure</th>
            </tr>
          </thead>
          <tbody>
              
            {% for item in liste_beneficiaire_coach %}
            <tr>
              <td><a href="{{ item.get_absolute_url }}"> {{ item.nom_prenom }} </a></td>
              <td>{{ item.date_inscription }} </td>
              <td>{{ item.groupe }} </td>
              <td>{{ item.groupe.structure }} </td>
             
              {% endfor %}
             
            </tr>
          </tbody>
        </table>
      </div>
    </div>



    
    {% endblock %}

application_adyma/templates/application_adyma/vues/structure.html
{% extends "application_adyma/base.html" %}
{% block content %}
<div class="card">
    <div class="card-body">
      <h3>Liste des bénéficiaires de {{ user.username }}</h3>
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th scope="col-2">Nom-Prenom </th>
              <th scope="col-2">Date d'inscription</th>
              <th scope="col-2">Groupe</th>
            </tr>
          </thead>
          <tbody>
              
            {% for instance in liste_beneficiaire_structure %}
            <tr>
              <td>{{ instance.nom_prenom }}</td>
              <td>{{ instance.date_inscription }}</td>

              <td>{{ instance.groupe.nom_groupe }}</td>       
            </td>
              {% endfor %}

            </tr>
          </tbody>
        </table>
      </div>
    </div>

<!-- Feuille d'inscription -->
<div class="card">
  <div class="card-body">
    <h3 class="text-center">Feuille d'inscription de {{ user.username }}</h3>
    <div class="row justify-content">
      {% if structure_inscription.exists %} 
      <div class="col-8">
        <table class="table table-bordered table-hover">
          {% for instance in structure_inscription %}
          <tbody>

            <tr>
              <td class="col-4 text-uppercase fw-bold">Date d'inscription</td>
              <td class="col-4">{{ instance.date_inscription_structure }}</td>
            </tr>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Adresse</td>
              <td class="col-4">{{ instance.adresse_structure }}</td>
            </tr>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Ville</td>
              <td class="col-4">{{ instance.ville_structure }}</td>
            </tr>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Téléphone</td>
              <td class="col-4">{{ instance.telephone_structure }}</td>
            </tr>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Nombre de résidents</td>
              <td class="col-4">{{ instance.nombre_residents }}</td>
            </tr>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Nom du directeur</td>
              <td class="col-4">{{ instance.nom_directeur_structure }}</td>
            </tr>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Mail du directeur</td>
              <td class="col-4">{{ instance.mail_directeur_structure }}</td>
            </tr>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Téléphone du directeur</td>
              <td class="col-4">{{ instance.telephone_directeur_structure }}</td>
            </tr>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Autres salariés référents</td>
              <td class="col-4">{{ instance.autres_salaries_referents }}</td>
            </tr>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Nom - Prénom Coach 1</td>
              <td class="col-4">{{ instance.nom_prenom_coach_1 }}</td>
            </tr>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Nom - Prénom Coach 2</td>
              <td class="col-4">{{ instance.nom_prenom_coach_2 }}</td>
            </tr>
          </tbody>
          {% endfor %}
        </table>
      </div>
      {% else %}
        <p> La structure {{ user.username}} ne possède pas de feuille d'inscription</p>
      {% endif %}
    </div>
  </div>
</div>
<!-- Diagnostic Structurel -->
<div class="card">
  <div class="card-body">
    <h3 class="text-center">Diagnostic Structurel de {{ user.username }}</h3>
    <div class="row justify-content">
      {% if structure_inscription.exists %} 
      <div class="col-8">
        <table class="table table-bordered table-hover">
          {% for instance in diagnostic_structurel %}
          <tbody>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Date diagnostic structurel</td>
              <td class="col-4">{{ instance.date_diagnostic }}</td>
            </tr>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Adaptabilité de l'environnement et de la structure à la mobilité (escaliers, barres d'appuis, luminosité...)</td>
              <td class="col-4">{{ instance.get_adaptation_env_struc_mobi_display }}</td>
            </tr>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Nombre d'activité (mémoire, gym, informatique...) par semaine proposées</td>
              <td class="col-4">{{ instance.get_nombre_activite_semaine_display }}</td>
            </tr>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Salle d'activité réservée pour les activités physiques</td>
              <td class="col-4">{{ instance.get_salle_activite_reservee_display }}</td>
            </tr>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Matériel d'activité physique (tapis, machines, espalier)</td>
              <td class="col-4">{{ instance.get_materiel_activite_physique_display }}</td>
            </tr>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Liens réguliers avec organisation extérieure</td>
              <td class="col-4">{{ instance.get_liens_reguliers_org_ext_display }}</td>
            </tr>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Nombre de personnes extérieures venant réulièrement dans l'établissement</td>
              <td class="col-4">{{ instance.get_nb_personnes_ext_reg_etablissement_display }}</td>
            </tr>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Sorties et séjours organisés dans l'année</td>
              <td class="col-4">{{ instance.get_sorties_sejours_org_annee_display }}</td>
            </tr>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Nombre de commerces de proximité (< 250m) </td>
              <td class="col-4">{{ instance.get_nb_commerces_prox_display }}</td>
            </tr>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Nombre de parcs à proximité (< 500m)</td>
              <td class="col-4">{{ instance.get_nb_parcs_prox_display }}</td>
            </tr>
            <tr>
              <td class="col-4 text-uppercase fw-bold">Transports en commun à proximité (en mètres)</td>
              <td class="col-4">{{ instance.get_transports_communs_prox_display }}</td>
            </tr>
            <tr class="total-alerte fw-bold">
              <td class="col-4 lighter ">Total point diagnostic structurel / 10</td>
              <td class="col-4">{{ total_point_structurel }}</td>
            </tr>
          </tbody>
          {% endfor %}
        </table>
      </div>
      {% else %}
        <p> La structure {{ detail_beneficiaire.nom_prenom }} ne possède pas de feuille d'inscription</p>
      {% endif %}
    </div>
  </div>
</div>
<div class="card">
  <div class="card-body">
    <h3 class="text-center">Présence de {{ user.username }}</h3>
    <div class="row justify-content">
      <div class="col-8">
        <table class="table table-bordered table-hover">
          <tbody>
            <tr>
              <td class="col-8 text-uppercase fw-bold"> Nombre de sorties moyen par semaine des résidents </td>
              <td class="col-2">{{ avg_nb_sortie_semaine.nb_moy_sort }}</td>
            </tr>
            <tr>
              <td class="col-8 text-uppercase fw-bold"> Durée moyenne des sorties extérieures des résidents </td>
              <td class="col-2">{{ avg_duree_moyenne_sortie_ext.nb_moy_sort }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>










    
    {% endblock %}